# site settings
title: Ankiydv
subtitle: by HTML5 UP
email: ankit.2000y@gmail.com
description: This is my personal Portfolio.
baseurl: "/Portfolio" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: Rewari
state: HR
zip_code: 
country: India
phone: (870) 871-2780

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/ankiydv
googleplus_url: 
instagram_url: https://instagram.com/ankiydv
linkedin_url: https://www.linkedin.com/in/ankiydv
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ankiydv

# build settings
markdown: kramdown

sass:
  style: compressed
